// Full country names for the 3-letter FIFA codes used in data/soccer/ratings.json.
// Used to render readable labels in the World Cup UI (the dropdown otherwise
// only shows the code, e.g. "SWE").
export const COUNTRY_NAMES: Record<string, string> = {
  ARG: "Argentina",
  ESP: "Spain",
  FRA: "France",
  ENG: "England",
  BRA: "Brazil",
  COL: "Colombia",
  POR: "Portugal",
  NED: "Netherlands",
  NOR: "Norway",
  SUI: "Switzerland",
  MEX: "Mexico",
  GER: "Germany",
  CRO: "Croatia",
  ECU: "Ecuador",
  JPN: "Japan",
  MAR: "Morocco",
  BEL: "Belgium",
  DEN: "Denmark",
  ITA: "Italy",
  TUR: "Türkiye",
  SEN: "Senegal",
  URU: "Uruguay",
  AUT: "Austria",
  PAR: "Paraguay",
  AUS: "Australia",
  ALG: "Algeria",
  USA: "United States",
  UKR: "Ukraine",
  NGA: "Nigeria",
  IRN: "Iran",
  CAN: "Canada",
  CIV: "Ivory Coast",
  SWE: "Sweden",
  EGY: "Egypt",
  SRB: "Serbia",
  KOR: "South Korea",
  CHI: "Chile",
  COD: "DR Congo",
  HUN: "Hungary",
  POL: "Poland",
  PER: "Peru",
  SCO: "Scotland",
  WAL: "Wales",
  CZE: "Czechia",
  PAN: "Panama",
  UZB: "Uzbekistan",
  JOR: "Jordan",
  CMR: "Cameroon",
  CRC: "Costa Rica",
  KSA: "Saudi Arabia",
  GHA: "Ghana",
  TUN: "Tunisia",
  RSA: "South Africa",
  NZL: "New Zealand",
  QAT: "Qatar",
};
